### ISSUE TITLE
"File (null) not found." error

### ISSUE THREAD

**Issue by timb** [ansilove/AnsiLove-C#5]
after compiling on 32-bit linux (ubuntu), i get this output when trying to generate pngs:

    ~/src/AnsiLove-C$ ./ansilove ansis/rad-love.ans -i
    AnsiLove/C 2.2.1 - ANSi / ASCII art to PNG converter
    Copyright (C) 2011-2015 Stefan Vogt, Brian Cassidy, Frederic Cambus.
    ./ansilove: option requires an argument -- 'i'

    File (null) not found.

and

    ~/src/AnsiLove-C$ ./ansilove ansis/rad-love.ans -o out
    AnsiLove/C 2.2.1 - ANSi / ASCII art to PNG converter
    Copyright (C) 2011-2015 Stefan Vogt, Brian Cassidy, Frederic Cambus.

    File (null) not found.

if it is any help, CMakeFiles/CMakeOutput.log is at http://pastebin.com/raw.php?i=d3aKT7aD

**Comment by fcambus** [comment]
Hello!

Yes, that happens because I changed the semantics of flags (now using getopt for this) but didn't update usage information nor documentation, and temporary used the -i flag to specify the file name. Still a work in progress though.

My last commit should allow you to generate files without using the -i flag.

Try :
./ansilove ansis/rad-love.ans
./ansilove -o out.png ansis/rad-love.ans

**Comment by timb** [comment]
ah! thanks, that works
